### ISSUE TITLE
button shown transparent instead of facebook blue

### ISSUE THREAD

**Issue by ohadpartuck** [brentvatne/react-native-linear-gradient#10]
for me , the button is shown transparent

```
var LinearGradient = require('react-native-linear-gradient');
<View style={styles.container}>

 <View style={{backgroundColor: 'transparent'}}>
   <TouchableOpacity onPress={this.login}>
      <LinearGradient colors={['#4c669f', '#3b5998', '#192f6a']} style={{
                paddingLeft: 15,
                paddingRight: 15,
                borderRadius: 5
              }}>
           <Text style={styles.buttonText}>
                  Sign in with Facebook
           </Text>
     </LinearGradient>
   </TouchableOpacity>
  </View>

</View>
```

<img width="321" alt="screen shot 2015-07-18 at 1 41 01 pm" src="https://cloud.githubusercontent.com/assets/2236337/8761299/a5fe19e0-2d52-11e5-9ff2-a01222184450.png">

**Comment by ohadpartuck** [comment]
I'm sure it's unrelated but the `TouchableOpacity` functionality doesn't work, I had to replace it with `TouchableHighlight` but i'm sure it shouldn't effect the button syling.

**Comment by nickhudkins** [comment]
Take a look at Step 3 in https://github.com/brentvatne/react-native-linear-gradient/blob/master/README.md.

You'll need to make sure that libBVLinearGradient.a has been added to Build Phases of your project.

I'll talk to @brentvatne to see if TouchableOpacity playing nicely here would be something we want to support.

My recommendation if you've got a LinearGradient view that is touchable, you'd want to swap the gradient colors or start/stop values rather than adjusting the opacity of the entire view.

Let me know if adding libBVLinearGradient.a to your Build Phases resolves your original issue.

**Comment by brentvatne** [comment]
Is TouchableOpacity not working with it right now @nickhudkins? Weird, I think it should.

**Comment by nickhudkins** [comment]
I have not tested. I can take a look later and make sure it does or doesn't.

**Comment by dgladkov** [comment]
Tested TouchableOpacity on both Android and iOS, works as expected. TouchableHighlight is broken though because it relies on backgroundColor, but as @nickhudkins suggested it's better to adjust gradient colors manually in this case.
