### ISSUE TITLE
[Android] borderRadius on LinearGradient's style is not supported

### ISSUE THREAD

**Issue by frantic** [brentvatne/react-native-linear-gradient#47]
Code: https://gist.github.com/frantic/c5a335d5cfb9384ed6e9
Screenshot:

<img width="953" alt="screen shot 2015-12-15 at 11 06 48 am" src="https://cloud.githubusercontent.com/assets/192222/11821081/945dea4a-a31c-11e5-8cb3-0d793b86fa41.png">

**Comment by dgladkov** [comment]
This a result of how borderRadius works in Android, issue with a general example documented here: https://github.com/facebook/react-native/issues/3198

Possible solutions:
1. Implement `LinearGradientView` as `ReactViewGroup` subclass, thus removing the need to wrap it in the container (see [index.android.js#L17-L25](https://github.com/brentvatne/react-native-linear-gradient/blob/b185a90f81792081debfd2abd85eb48fe2e32567/index.android.js#L17-L25)). Will require copying A LOT of code from https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/views/view
2. Apply borderRadius from styles prop on both container and `LinearGradientView`. Requires ugly style introspection, but otherwise works fine. (see [android-borders branch](https://github.com/brentvatne/react-native-linear-gradient/tree/android-borders))
3. Document it as a limitation of Android version and wait for a fix to land in react-native

If you think solution 2 is good enough I can merge it into master.

**Comment by frantic** [comment]
@dgladkov I think style introspection is okay in this case, as long as the reason is documented in sources and the abstraction doesn't leak into developer's code. I've added [a suggestion about `flattenStyle`](https://github.com/brentvatne/react-native-linear-gradient/commit/bb0373783c9a98394d6c425286f6d2679cf6ec6d#commitcomment-15639631).

**Comment by dgladkov** [comment]
Fixed in 1.4.0
