### ISSUE TITLE
Broken in RN 0.27 (Android and iOS)

### ISSUE THREAD

**Issue by KarlosQ** [brentvatne/react-native-linear-gradient#87]
In the last version (0.27) crash with this error:

![sin titulo](https://cloud.githubusercontent.com/assets/15233913/15900736/da3aa558-2da0-11e6-8336-092c72edc618.png)

**Comment by KarlosQ** [comment]
It is fixed using import LinearGradient from 'react-native-linear-gradient';

**Comment by dgladkov** [comment]
This issue is caused by `module.exports` being replaced with ES2015 `export default` in this commit https://github.com/brentvatne/react-native-linear-gradient/commit/366239e441a40d329fad7defb775f256f420d448. This is a breaking change and it definitely called for a major version bump, but I totally forgot about this case.

It's probably a good idea to use `module.exports` to have same require/import behavior, but I don't know how many people still use require in their react-native codebase. If it causes problems for more people, I'll revert this change in the next patch release
